import type { Metadata } from "next";
import { fontSans, fontSerif } from "@/lib/fonts";
import { SHOW_FIXED_CTA } from "@/lib/config";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${fontSerif.variable} ${fontSans.variable} h-full antialiased motion-safe:scroll-smooth`}
    >
      <body
        className={`min-h-full flex flex-col bg-background text-ink ${
          SHOW_FIXED_CTA ? "pb-14 lg:pb-0" : ""
        }`}
      >
        {children}
      </body>
    </html>
  );
}
